apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kudo-manager
    controller-tools.k8s.io: "1.0"
  name: operatorversions.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: OperatorVersion
    plural: operatorversions
    singular: operatorversion
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        meta:
          type: object
        spec:
          properties:
            connectionString:
              description: ConnectionString defines a mustached string that can be
                used to connect to an instance of the Operator
              type: string
            crdVersion:
              type: string
            dependencies:
              items:
                properties:
                  crdVersion:
                    description: 'Version captures the requirements for what versions
                      of the above object are allowed Example: ^3.1.4'
                    type: string
                  referenceName:
                    description: Name specifies the name of the dependency.  Referenced
                      via this in defaults.config
                    type: string
                required:
                - referenceName
                - crdVersion
                type: object
              type: array
            operator:
              type: object
            parameters:
              items:
                properties:
                  default:
                    description: Default is a default value if no parameter is provided
                      by the instance
                    type: string
                  description:
                    description: Description captures a longer description of how
                      the variable will be used
                    type: string
                  displayName:
                    description: Human friendly crdVersion of the parameter name
                    type: string
                  name:
                    description: 'Name is the string that should be used in the template
                      file for example, if `name: COUNT` then using the variable `.Params.COUNT`'
                    type: string
                  required:
                    description: Required specifies if the parameter is required to
                      be provided by all instances, or whether a default can suffice
                    type: boolean
                  trigger:
                    description: Trigger identifies the plan that gets executed when
                      this parameter changes in the Instance object. Default is `update`
                      if present, or `deploy` if not present
                    type: string
                type: object
              type: array
            plans:
              description: Plans specify a map a plans that specify how to
              type: object
            tasks:
              description: List of all tasks available in this OperatorVersions
              items:
                properties:
                  kind:
                    type: string
                  name:
                    type: string
                  spec:
                    type: object
                type: object
              type: array
            templates:
              description: List of go templates YAML files that define the application
                operator instance
              type: object
            upgradableFrom:
              description: UpgradableFrom lists all OperatorVersions that can upgrade
                to this OperatorVersion
              items:
                type: object
              type: array
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
