apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: teststeps.kudo.dev
spec:
  group: kudo.dev
  names:
    kind: TestStep
    plural: teststeps
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        delete:
          description: Objects to delete at the beginning of the test step.
          items:
            type: object
          type: array
        index:
          format: int64
          type: integer
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          description: Override the default metadata. Set labels or override the test
            step name.
          type: object
        unitTest:
          description: Indicates that this is a unit test - safe to run without a
            real Kubernetes cluster.
          type: boolean
      required:
      - unitTest
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
