apiVersion: kudo.k8s.io/v1alpha1
apiVersion: kudo.k8s.io/v1alpha1
kind: Framework
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: canary-app
---
apiVersion: kudo.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: canary-v1
  namespace: default
spec:
  version: "1.0.0"
  connectionString: ""
  framework:
    name: canary-app
    kind: Framework
  templates:
      #change deployment name.
      # change image tag to canary
      # change
    deployment.yaml: |
      apiVersion: apps/v1beta2
      kind: Deployment
      metadata:
        name: {{ .Name }}
        labels:
          release: stable
          app:  appinfo
      spec:
        replicas: {{ .Params.Replicas }}
        selector:
          matchLabels:
            app: appinfo
        template:
          metadata:
            labels:
              app: appinfo
              release: stable
            annotations:
              prometheus.io/scrape: "true"
          spec:
            containers:
            - name: appinfo-containers
              image: runyonsolutions/appinfo:{{ .Params.Tag }}
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
              env:
              - name: MY_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: MY_POD_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              volumeMounts:
                - name: podinfo
                  mountPath: /opt/
            volumes:
                - name: podinfo
                  downwardAPI:
                    items:
                      - path: "labels"
                        fieldRef:
                          fieldPath: metadata.labels
    service.yaml: |
      apiVersion: v1
      kind: Service
      metadata:
        name: appinfo
        labels:
          app: appinfo
      spec:
        ports:
        - port: 8080
          protocol: TCP
        selector:
          app: appinfo
        type: LoadBalancer
  tasks:
    deployment:
      resources:
      - service.yaml
      - deployment.yaml
  parameters:
  - name: TAG
    description: "Docker image tag for runyonsolutions/appinfo"
    default: "master"
    required: false
    displayName: "Image Tag"
  - name: REPLICAS
    description: "Replicas for application"
    default: "3"
    required: false
    displayName: "Replicas"
  plans:
    deploy:
      strategy: serial
      phases:
        - name: all
          strategy: parallel
          steps:
            - name: services
              tasks:
              - services
            - name: deployment
              tasks:
              - deployment
    canary:
      strategy: serial
      phases:
        - name: deploy-canary
---
apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    framework: canary
  name: bird
spec:
  frameworkVersion:
    name: canary-v1
    namespace: default
    type: FrameworkVersion
  # Add fields here
  parameters:
    Tag: master
