apiVersion: maestro.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    framework: kafka
  name: small
spec:
  frameworkVersion:
    name: kafka-2.11-2.4.0
    namespace: default
    type: FrameworkVersion
  # Add fields here
  dependency:
    - referenaceName: zookeeper
      name: zk
      type: Instance
  parameters:
    KAFKA_ZOOKEEPER_URI: zk-zk-0.zk-hs:2181,zk-zk-1.zk-hs:2181,zk-zk-2.zk-hs:2181
    KAFKA_ZOOKEEPER_PATH: "/small"
    BROKERS_COUNT: "3"
