apiVersion: kudo.dev/v1alpha1
kind: Operator
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: toy
---
apiVersion: kudo.dev/v1alpha1
kind: OperatorVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: toy-v1
  namespace: default
spec:
  version: "1.0.0"
  connectionString: ""
  operator:
    name: Toy
    kind: Operator
  templates:
    serial.yaml: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        namespace: default
        name: serial-{{ .StepName }}
      spec:
        template:
          metadata:
            name: "{{ .StepName }}-serial-{{ .StepNumber }}"
          spec:
            restartPolicy: OnFailure
            containers:
            - name: bb
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - "sleep {{ .Params.Sleep }}"
    par.yaml: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: {{ .StepName }}-parallel-{{ .StepNumber }}
      spec:
        template:
          metadata:
            name: "{{ .StepName }}-parallel-{{ .StepNumber }}"
          spec:
            restartPolicy: Never
            containers:
            - name: bb
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - "sleep {{ .Params.Sleep }}"
  tasks:
    - name: par
      kind: Apply
      spec:
        resources:
          - par.yaml
    - name: serial
      kind: Apply
      spec:
        resources:
          - serial.yaml
  parameters:
  - name: SLEEP
    description: "how long to have the container sleep for before returning"
    default: "15"
    required: false
    displayName: "Sleep Time"
  plans:
    deploy:
      strategy: serial
      phases:
        - name: par
          strategy: parallel
          steps:
            - name: par-one
              tasks:
              - par
            - name: par-two
              tasks:
              - par
            - name: par-three
              tasks:
              - par
        - name: serial
          strategy: serial
          steps:
            - name: serial-one
              tasks:
              - serial
            - name: serial-two
              tasks:
              - serial
            - name: serial-three
              tasks:
              - serial
---
apiVersion: kudo.dev/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    operator: toy
  name: toy1
spec:
  operatorVersion:
    name: toy-v1
    namespace: default
    type: OperatorVersions
  # Add fields here
  parameters:
    Sleep: "30"
