apiVersion: maestro.k8s.io/v1alpha1
kind: Framework
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: toy
---
apiVersion: maestro.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: toy-v1
  namespace: default
spec:
  version: "1.0.0"
  connectionString: ""
  framework:
    name: Toy
    kind: Framework
  templates:
    serial.yaml: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        namespace: default
        name: serial-{{STEP_NAME}}
      spec:
        template:
          metadata:
            name: "{{STEP_NAME}}-serial-{{STEP_NUMBER}}"
          spec:
            restartPolicy: OnFailure
            containers:
            - name: bb
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - "sleep {{SLEEP}}"
    par.yaml: |
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: {{STEP_NAME}}-parallel-{{STEP_NUMBER}}
      spec:
        template:
          metadata:
            name: "{{STEP_NAME}}-parallel-{{STEP_NUMBER}}"
          spec:
            restartPolicy: Never
            containers:
            - name: bb
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
              - /bin/sh
              - -c
              - "sleep {{SLEEP}}"
  tasks:
    par:
      resources:
      - par.yaml
    serial:
      resources:
      - serial.yaml
  parameters:
  - name: SLEEP
    description: "how long to have the container sleep for before returning"
    default: "15"
    required: false
    displayName: "Sleep Time"
  plans:
    deploy:
      strategy: serial
      phases:
        - name: par
          strategy: parallel
          steps:
            - name: par-one
              tasks:
              - par
            - name: par-two
              tasks:
              - par
            - name: par-three
              tasks:
              - par
        - name: serial
          strategy: serial
          steps:
            - name: serial-one
              tasks:
              - serial
            - name: serial-two
              tasks:
              - serial
            - name: serial-three
              tasks:
              - serial
---
apiVersion: maestro.k8s.io/v1alpha1
kind: Instance
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    framework: toy
  name: toy1
spec:
  frameworkVersion:
    name: toy-v1
    namespace: default
    type: FrameworkVersions
  # Add fields here
  parameters:
    SLEEP: "30"
